### PR TITLE
Just change the position of the button

### PR DESCRIPTION
**Pull request by rakkyo150**
Just changed the position of the button because it was conflicting with the [NalulunaMenu](https://www.youtube.com/watch?v=qZMGXzJWrsk).
The values I changed are just a example, so you can change them as you like.
Difference

### CODE REVIEW

**Comment by rithik-b** [comment]
Can this PR be made to NalululunaMenu instead?
TakeMeToResults doesn't use a FloatingScreen unlike NalululunaMenu and I don't intend to use one either, the button currently looks out of place and that music player could be moved anywhere...

**Comment by rithik-b** [comment]
Nevermind it looks good, the screenshot was a bit confusing

**Comment by rithik-b** [comment]
Tried it in VR, the whole button is not clickable as a result of being out of bounds
Unfortunately I cannot accept this PR for that reason, would be better to PR/ask the other mod instead.

**Comment by rakkyo150** [comment]
Thanks for the confirmation.
As far as I know, NalulunaMenu does not use FloatingScreen. (Sorry if I'm wrong)
Sure, the music player can be moved anywhere, but that's the same for your mod, isn't it?
I understand that you don't intend to use FloatingScreen and that you want NalulunaMenu to support it, but NalulunaMenu was introduced to the world earlier.
Of course, you can't keep track of all the mods, so I know it's hard to avoid all conflicts .
However, I think you should take care of the UI position as much as possible so that it doesn't conflict with earlier others.

**Comment by rakkyo150** [comment]
I'm sorry that I couldn't find the bug that made it hard to click, because I didn't recognize the boundary and only checked in FPFC mode.
Just in case, I pushed the new pull-request branch of fork so that the button fits within the boundaries.
If you don't like it, you don't have to adopt it and you don't have to reply.
Sorry for the hard-to-read English.

**Comment by rithik-b** [comment]
No problem, I will try again one more time to see if it works

**Comment by rithik-b** [comment]
Merged!

**Comment by rakkyo150** [comment]
Thx!

**Pull request merged**
